import { useQuery } from '@tanstack/react-query'
import { useI18n } from '../i18n/I18nProvider'
import { apiFetch } from './api'
import type { BudgetReport } from './types'

const FETCH_MS = 120_000

function withTimeout(signal: AbortSignal | undefined, ms: number): AbortSignal {
  const ctrl = new AbortController()
  const t = window.setTimeout(() => ctrl.abort(), ms)
  const chain = () => {
    clearTimeout(t)
    ctrl.abort()
  }
  if (signal) {
    if (signal.aborted) chain()
    else signal.addEventListener('abort', chain, { once: true })
  }
  return ctrl.signal
}

/**
 * Loads the budget report for the selected UI language. Spanish and Chinese are
 * merged from stored translation payloads in the API database (generated by the
 * server when a report is saved, or on first request).
 */
export function useTranslatedReport(report: BudgetReport | null) {
  const { locale } = useI18n()
  const targetLocale = locale === 'es' || locale === 'zh' ? locale : null

  const query = useQuery({
    queryKey: ['report-translation', report?.id, report?.updatedAt, targetLocale],
    queryFn: ({ signal }) =>
      apiFetch<{ report: BudgetReport }>(
        `/api/reports/localized?id=${encodeURIComponent(report!.id)}&locale=${targetLocale}`,
        { signal: withTimeout(signal, FETCH_MS) },
      ).then((r) => r.report),
    enabled: Boolean(report && targetLocale),
    staleTime: Number.POSITIVE_INFINITY,
    gcTime: 1000 * 60 * 60,
    refetchOnMount: 'always',
    retry(failureCount, error) {
      if (error instanceof Error && error.name === 'AbortError') {
        return false
      }
      return failureCount < 2
    },
    retryDelay: (i) => Math.min(1500 * 2 ** i, 8000),
  })

  const displayReport: BudgetReport | null = !report
    ? null
    : !targetLocale
      ? report
      : (query.data ?? report)

  const isTranslating = Boolean(targetLocale && report && query.isFetching)

  return {
    displayReport,
    isTranslating,
    translationError: query.error,
  }
}
